// Integração de Páginas Web com Banco de Dados/clientes/livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivros } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';
import { Livro } from './model/Livro';

const controleLivros = new ControleLivros();
const controleEditora = new ControleEditora();

export default function LivroDados() {
  const navigate = useNavigate();
  const editoras = controleEditora.getEditoras();

  const [titulo, setTitulo] = useState('');
  const [resumo, setResumo] = useState('');
  const [codEditora, setCodEditora] = useState(editoras[0] ? editoras[0].codEditora : 0);
  const [autores, setAutores] = useState('');

  const incluir = (event) => {
    event.preventDefault();
    const autoresArray = autores.split('\n').filter((a) => a.trim() !== '');
    // Criando o objeto Livro com código vazio conforme instruções
    const livro = new Livro('', Number(codEditora), titulo, resumo, autoresArray);

    controleLivros.incluir(livro).then(() => {
      navigate('/');
    });
  };

  return (
    <main className="container mt-4">
      <h1>Dados do Livro</h1>
      <form onSubmit={incluir} className="mt-3">
        <div className="mb-3">
          <label htmlFor="titulo" className="form-label">Título</label>
          <input
            type="text"
            className="form-control"
            id="titulo"
            value={titulo}
            onChange={(e) => setTitulo(e.target.value)}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="resumo" className="form-label">Resumo</label>
          <textarea
            className="form-control"
            id="resumo"
            rows="3"
            value={resumo}
            onChange={(e) => setResumo(e.target.value)}
            required
          />
        </div>

        <div className="mb-3">
          <label htmlFor="codEditora" className="form-label">Editora</label>
          <select
            className="form-select"
            id="codEditora"
            value={codEditora}
            onChange={(e) => setCodEditora(Number(e.target.value))}
          >
            {editoras.map((editora) => (
              <option key={editora.codEditora} value={editora.codEditora}>
                {editora.nome}
              </option>
            ))}
          </select>
        </div>

        <div className="mb-3">
          <label htmlFor="autores" className="form-label">Autores (1 por linha)</label>
          <textarea
            className="form-control"
            id="autores"
            rows="3"
            value={autores}
            onChange={(e) => setAutores(e.target.value)}
            required
          />
        </div>

        <button type="submit" className="btn btn-primary">Salvar Dados</button>
      </form>
    </main>
  );
}

// Integração de Páginas Web com Banco de Dados/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
  standalone: false
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n').filter(a => a.trim() !== '');
    this.livro.codEditora = Number(this.livro.codEditora);
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main class="container mt-4">
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate class="mt-3">
    <div class="mb-3">
      <label for="titulo" class="form-label">Título</label>
      <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required>
    </div>

    <div class="mb-3">
      <label for="resumo" class="form-label">Resumo</label>
      <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo" rows="3"></textarea>
    </div>

    <div class="mb-3">
      <label for="codEditora" class="form-label">Editora</label>
      <select class="form-select" id="codEditora" [(ngModel)]="livro.codEditora" name="codEditora" required>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>

    <div class="mb-3">
      <label for="autoresForm" class="form-label">Autores (1 por linha)</label>
      <textarea class="form-control" id="autoresForm" [(ngModel)]="autoresForm" name="autoresForm" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>
